apiVersion: v1
kind: Secret
metadata:
  name: {{ include "health-chart.fullname" . }}
  labels:
    {{- include "health-chart.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "health-chart.serviceAccountName" . }}

type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
    {{ $key }}: {{ $value | b64enc | quote }}
    {{- end }}
